name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate report
        run: |
          pytest --junitxml=reports/test_results.xml
          
      - name: Upload test results to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: reports/test_results.xml